# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12c96c0093ee8e679a796438face96c652dbf2d04bdce71aeaceb883c78f5ecede9c751c2f70acbd404210807482680a8d42390527c2152122cbd0974e24e363

test:
  secret_key_base: 3cf945f012058f16abe18903345afff5ae1cbd178aff2b302d160d22249263f86f76f7bf4c53bf6d62a1d7a10d1957f60215e3611ad838f2644efcd7633cd0f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
